version: '3'
services:
  rabbitMQ:
   image: rabbitmq:3-management
   container_name: 'rabbitmq_container'
   environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
   ports:
    - 8050:15672
    - 5672:5672
   expose:
    - 5672
   networks: 
    - elibarynet2023

  elibary_sql:
    container_name: app_db
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Word5678?
      - MSSQL_PID=Developer
    ports:
      - 1405:1433
    expose:
      - 1433
    networks:
      - elibarynet2023

  elibary_api:
    restart: unless-stopped
    build:
      context: ./eBiblioteka
    environment:
      - ConnectionStrings:Main=Server=elibary_sql, 1433;Database=200200;User=sa;Password=Word5678?;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 7034:7034
    networks:
      - elibarynet2023
    links:
      - elibary_sql
    depends_on:
      - elibary_sql
      - rabbitMQ


  auxiliary:
    restart: unless-stopped
    build:
      context: ./Auxiliary
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 7138:7138
    networks:
      - elibarynet2023
    depends_on:
      - rabbitMQ
      
    
    
  
networks:
  elibarynet2023:
    driver: bridge